version: '3.9'
services:
  postgres:
    build:
        context: .
        dockerfile: Dockerfile
    image: dot-golang-pg-144
    volumes:
       - ./pgdata:/var/lib/postgresql/data
    container_name: dot-golang-pg-144
    restart: unless-stopped 
    environment:
        POSTGRES_DB: dot-golang
        POSTGRES_USER: dot-golang
        POSTGRES_PASSWORD: dot-golang*144
    ports:
      - 5144:5432
    networks:
      - dot-golang-network

networks:
  dot-golang-network:
    external: true